// Copyright (c) 2022 YA-androidapp(https://github.com/YA-androidapp) All rights reserved.


const fontNames = [
    "Academy Engraved LET",
    "American Typewriter",
    "AmericanTypewriter-Condensed",
    "AmericanTypewriter-CondensedBold",
    "AmericanTypewriter-CondensedLight",
    "Andale Mono",
    "Apple Chancery",
    "Apple LiGothic",
    "Apple LiSung",
    "Apple SD Gothic Neo",
    "Apple Symbols",
    "AppleGothic",
    "AppleMyungjo",
    "AppleSDGothicNeo-Bold",
    "AppleSDGothicNeo-ExtraBold",
    "AppleSDGothicNeo-Heavy",
    "AppleSDGothicNeo-Light",
    "AppleSDGothicNeo-Medium",
    "AppleSDGothicNeo-SemiBold",
    "AppleSDGothicNeo-Thin",
    "AppleSDGothicNeo-UltraLight",
    "Arial Black",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Arial Unicode MS",
    "Arial",
    "Avenir Next Condensed",
    "Avenir Next Condensed",
    "Avenir Next",
    "Avenir Next",
    "Avenir-Black",
    "Avenir-Heavy",
    "Avenir-Light",
    "Avenir-Medium",
    "Avenir-Roman",
    "Avenir",
    "AvenirNext-Bold",
    "AvenirNext-DemiBold",
    "AvenirNext-Heavy",
    "AvenirNext-Medium",
    "AvenirNext-UltraLight",
    "AvenirNextCondensed-Bold",
    "AvenirNextCondensed-DemiBold",
    "AvenirNextCondensed-Heavy",
    "AvenirNextCondensed-Medium",
    "AvenirNextCondensed-UltraLight",
    "Ayuthaya",
    "Bahnschrift",
    "Bangla MN",
    "Bangla Sangam MN",
    "Baoli SC",
    "Baoli TC",
    "Baskerville-Bold",
    "Baskerville-SemiBold",
    "Baskerville",
    "Baskerville",
    "BiauKai",
    "Big Caslon",
    "BIZ UDGothic",
    "BIZ UDMincho",
    "BIZ UDPGothic",
    "BIZ UDPMincho",
    "BIZ UDPゴシック",
    "BIZ UDP明朝",
    "BIZ UDゴシック",
    "BIZ UD明朝",
    "BM Dohyeon",
    "BM Hanna 11yrs Old",
    "BM Hanna Air",
    "BM Hanna Pro",
    "BM Jua",
    "BM Kirang Haerang",
    "BM Yeonsung",
    "Bodoni 72 Oldstyle",
    "Bodoni 72 Smallcaps",
    "Bodoni 72",
    "Bradley Hand",
    "Brush Script MT",
    "Calibri",
    "Cambria Math",
    "Cambria",
    "Candara",
    "Chalkboard SE",
    "Chalkboard SE",
    "Chalkboard SE",
    "Chalkboard",
    "ChalkboardSE-Light",
    "Chalkduster",
    "Charter",
    "Cochin",
    "Comic Sans MS",
    "Comic Sans MS",
    "Consolas",
    "Constantia",
    "Copperplate",
    "Corbel",
    "Courier New",
    "Courier",
    "Courier",
    "Devanagari Sangam MN",
    "Didot",
    "DIN Alternate",
    "DIN Condensed",
    "Ebrima",
    "Euphemia UCAS",
    "FixedSys",
    "Franklin Gothic Medium",
    "Futura-CondensedExtraBold",
    "Futura-CondensedMedium",
    "Futura",
    "FZLTTHB--B51-0",
    "FZLTTHK--GBK1-0",
    "FZLTZHB--B51-0",
    "FZLTZHK--GBK1-0",
    "Gabriola",
    "Gadugi",
    "Galvji",
    "Geneva",
    "Georgia",
    "Gujarati Sangam MN",
    "GungSeo",
    "Gurmukhi MN",
    "Gurmukhi Sangam MN",
    "Hannotate SC",
    "Hannotate TC",
    "HanziPen SC",
    "HanziPen TC",
    "HeadLineA",
    "Hei",
    "Heiti SC",
    "Heiti TC",
    "Helvetica Neue",
    "Helvetica Neue",
    "Helvetica",
    "HelveticaNeue-CondensedBlack",
    "HelveticaNeue-CondensedBold",
    "HelveticaNeue-Light",
    "HelveticaNeue-Thin",
    "Herculanum",
    "Hiragino Maru Gothic ProN",
    "Hiragino Mincho ProN",
    "Hiragino Sans CNS",
    "Hiragino Sans GB",
    "Hiragino Sans W0",
    "Hiragino Sans W1",
    "Hiragino Sans W2",
    "Hiragino Sans W3",
    "Hiragino Sans W4",
    "Hiragino Sans W5",
    "Hiragino Sans W6",
    "Hiragino Sans W7",
    "Hiragino Sans W8",
    "Hiragino Sans W9",
    "HiraginoSans-W0",
    "HiraginoSans-W1",
    "HiraginoSans-W2",
    "HiraginoSans-W3",
    "HiraginoSans-W4",
    "HiraginoSans-W5",
    "HiraginoSans-W6",
    "HiraginoSans-W7",
    "HiraginoSans-W8",
    "HiraginoSans-W9",
    "Hoefler Text",
    "HoeflerText-Black",
    "HoeflerText-Regular",
    "Impact",
    "InaiMathi",
    "Ink Free",
    "Javanese Text",
    "Kai",
    "Kaiti SC",
    "Kaiti SC",
    "Kaiti TC",
    "Kannada MN",
    "Kannada Sangam MN",
    "Kefa",
    "Khmer MN",
    "Khmer Sangam MN",
    "Klee",
    "Kohinoor Bangla",
    "Kohinoor Devanagari",
    "Kohinoor Telugu Bold",
    "Kohinoor Telugu Light",
    "Kohinoor Telugu Semibold",
    "Kohinoor Telugu",
    "KohinoorBangla-Bold",
    "KohinoorBangla-Light",
    "KohinoorBangla-Medium",
    "KohinoorBangla-Regular",
    "KohinoorBangla-Semibold",
    "KohinoorDevanagari-Bold",
    "KohinoorDevanagari-Light",
    "KohinoorDevanagari-Medium",
    "KohinoorDevanagari-Regular",
    "KohinoorDevanagari-Semibold",
    "Krungthep",
    "Lantinghei SC",
    "Lantinghei TC",
    "Lantinghei TC",
    "Lao MN",
    "Lao Sangam MN",
    "Leelawadee UI Semilight",
    "Leelawadee UI",
    "Libian SC",
    "Libian TC",
    "LiHei Pro",
    "LingWai SC",
    "LingWai TC",
    "LiSong Pro",
    "Lucida Console",
    "Lucida Grande",
    "Lucida Sans Unicode",
    "Luminari",
    "Malayalam MN",
    "Malayalam Sangam MN",
    "Malgun Gothic Semilight",
    "Malgun Gothic",
    "Marker Felt",
    "Meiryo UI",
    "Meiryo UI",
    "Meiryo",
    "Menlo",
    "Microsoft Himalaya",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei UI Light",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft YaHei Light",
    "Microsoft YaHei UI Light",
    "Microsoft YaHei UI",
    "Microsoft YaHei",
    "Microsoft Yi Baiti",
    "MingLiU_HKSCS-ExtB",
    "MingLiU-ExtB",
    "Modern",
    "Monaco",
    "Mongolian Baiti",
    "MS Gothic",
    "MS Mincho",
    "MS PGothic",
    "MS PMincho",
    "ＭＳ Ｐゴシック",
    "ＭＳ Ｐ明朝",
    "MS Sans Serif",
    "MS Serif",
    "MS UI Gothic",
    "ＭＳ ゴシック",
    "ＭＳ 明朝",
    "Mukta Mahee",
    "Mv Boli",
    "Myanmar MN",
    "Myanmar Sangam MN",
    "Myanmar Text",
    "Nanum Brush Script",
    "Nanum Pen Script",
    "NanumGothic",
    "NanumGothic",
    "NanumMyeongjo",
    "Nirmala UI Semilight",
    "Nirmala UI",
    "Noteworthy",
    "Noto Sans JP",
    "Noto Serif JP",
    "NSimSun",
    "Optima",
    "Oriya MN",
    "Oriya Sangam MN",
    "Osaka-Mono",
    "Osaka",
    "Osaka−等幅",
    "Palatino Linotype",
    "Palatino",
    "Papyrus-Condensed",
    "Papyrus",
    "Party LET",
    "PCMyungjo",
    "Phosphate Solid",
    "Phosphate-Solid",
    "Phosphate",
    "PilGi",
    "PingFang HK",
    "PingFang SC",
    "PingFang TC",
    "PingFangHK-Light",
    "PingFangHK-Medium",
    "PingFangHK-Semibold",
    "PingFangHK-Thin",
    "PingFangHK-Ultralight",
    "PingFangSC-Light",
    "PingFangSC-Medium",
    "PingFangSC-Semibold",
    "PingFangSC-Thin",
    "PingFangSC-Ultralight",
    "PingFangTC-Light",
    "PingFangTC-Medium",
    "PingFangTC-Semibold",
    "PingFangTC-Thin",
    "PingFangTC-Ultralight",
    "Plantagenet Cherokee",
    "PMingLiU-ExtB",
    "PSL Ornanong Pro",
    "PT Mono",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Sans",
    "PT Serif Caption",
    "PT Serif",
    "Rockwell",
    "Roman",
    "Sathu",
    "Savoye LET",
    "Script",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Light",
    "Segoe UI SemiBold",
    "Segoe UI Semilight",
    "Segoe UI Symbol",
    "Segoe UI Variable Display",
    "Segoe UI Variable Small",
    "Segoe UI Variable Text",
    "Segoe UI",
    "Shree Devanagari 714",
    "SignPainter",
    "Silom",
    "SimSong",
    "SimSun-ExtB",
    "SimSun",
    "Sinhala MN",
    "Sinhala Sangam MN",
    "Sitka Banner",
    "Sitka Display",
    "Sitka Heading",
    "Sitka Small",
    "Sitka Subheading",
    "Sitka Text",
    "Skia-Regular_Black-Condensed",
    "Skia-Regular_Black-Extended",
    "Skia-Regular_Black",
    "Skia-Regular_Bold",
    "Skia-Regular_Condensed",
    "Skia-Regular_Extended",
    "Skia-Regular_Light-Condensed",
    "Skia-Regular_Light-Extended",
    "Skia-Regular_Light",
    "Skia",
    "Small Fonts",
    "Snell Roundhand",
    "Songti SC",
    "Songti SC",
    "Songti TC",
    "STFangsong",
    "STHeiti",
    "STHeitiSC",
    "STHeitiTC",
    "STIXGeneral",
    "STKaiti",
    "STKaitiSC-Black",
    "STKaitiTC-Black",
    "STSong",
    "STXingkai-SC-Bold",
    "STXingkai-TC-Bold",
    "STYuanti-SC-Bold",
    "STYuanti-SC-Light",
    "STYuanti-TC-Bold",
    "STYuanti-TC-Light",
    "Sukhumvit Set",
    "SukhumvitSet-Light",
    "SukhumvitSet-Thin",
    "Sylfaen",
    "System",
    "Tahoma",
    "Tahoma",
    "Tamil MN",
    "Tamil Sangam MN",
    "Telugu MN",
    "Telugu Sangam MN",
    "Terminal",
    "Thonburi",
    "Times New Roman",
    "Times",
    "Toppan Bunkyu Gothic",
    "Toppan Bunkyu Midashi Gothic",
    "Toppan Bunkyu Midashi Mincho",
    "Toppan Bunkyu Mincho",
    "Trattatello",
    "Trebuchet MS",
    "Tsukushi A Round Gothic",
    "Tsukushi B Round Gothic",
    "UD Digi Kyokasho N-B",
    "UD Digi Kyokasho N-R",
    "UD Digi Kyokasho NK-B",
    "UD Digi Kyokasho NK-R",
    "UD Digi Kyokasho NP-B",
    "UD Digi Kyokasho NP-R",
    "UD デジタル 教科書体 N-B",
    "UD デジタル 教科書体 N-R",
    "UD デジタル 教科書体 NK-B",
    "UD デジタル 教科書体 NK-R",
    "UD デジタル 教科書体 NP-B",
    "UD デジタル 教科書体 NP-R",
    "Verdana",
    "Wawati SC",
    "Wawati TC",
    "Weibei SC",
    "Weibei TC",
    "Xingkai SC",
    "Xingkai TC",
    "Yu Gothic UI Bold",
    "Yu Gothic UI Light",
    "Yu Gothic UI Semibold",
    "Yu Gothic UI Semilight",
    "Yu Gothic UI",
    "Yu Gothic",
    "Yu Mincho Light",
    "Yu Mincho",
    "Yuanti SC",
    "Yuanti SC",
    "Yuanti TC",
    "Yuanti TC",
    "YuGothic",
    "YuKyokasho Yoko",
    "YuKyokasho",
    "YuMin-Extrabold",
    "YuMincho +36p Kana",
    "YuMincho",
    "Yuppy SC",
    "Yuppy TC",
    "Zapfino",
    "クレー",
    "ヒラギノ丸ゴ ProN W4",
    "ヒラギノ明朝 ProN W3",
    "ヒラギノ明朝 ProN",
    "ヒラギノ角ゴシック W0",
    "ヒラギノ角ゴシック W1",
    "ヒラギノ角ゴシック W2",
    "ヒラギノ角ゴシック W3",
    "ヒラギノ角ゴシック W4",
    "ヒラギノ角ゴシック W5",
    "ヒラギノ角ゴシック W6",
    "ヒラギノ角ゴシック W7",
    "ヒラギノ角ゴシック W8",
    "ヒラギノ角ゴシック W9",
    "メイリオ",
    "儷宋 Pro",
    "凸版文久ゴシック",
    "凸版文久明朝",
    "凸版文久見出しゴシック",
    "凸版文久見出し明朝",
    "游ゴシック Light",
    "游ゴシック",
    "游ゴシック体",
    "游ゴシック体",
    "游教科書体 横用",
    "游教科書体",
    "游明朝 Demibold",
    "游明朝体",
    "游明朝体+36ポかな",
    "筑紫A丸ゴシック",
    "筑紫B丸ゴシック",
    "黒体-簡",
    "黒体-繁"
];

const getAvailableFonts = () => {
    return fontNames.filter(function (element) {
        return isInstalledFont(element);
    });
}

const initializeFontSelection = () => {
    var select = document.getElementById("textbox-fontname");

    getAvailableFonts().forEach(element => {
        var option = document.createElement("option");
        option.text = element;
        option.value = element;
        select.appendChild(option);
    });
}
